version: 2
jobs:
  build:
    docker:
      - image: renovate/buildpack-deps
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Configure Docker Hub
          command: echo "$DOCKERHUB_PASS" | docker login -u "$DOCKERHUB_USERNAME" --password-stdin
      - run:
          name: Run Renovate Docker Build Script
          command: ./build.sh
workflows:
  version: 2
  build:
    jobs:
      - build
