name: Test CI

on: [push, pull_request]

env:
  PLATFORM: linux/amd64
  DOCKER_CACHE_TAG: _cache
  DOCKER_REPO: renovate/node

jobs:
  build:
    name: Build image
    runs-on: ubuntu-latest

    timeout-minutes: 20

    steps:
      - name: Set up Docker Buildx
        id: buildx
        uses: crazy-max/ghaction-docker-buildx@v1
        with:
          version: v0.3.1

      - uses: actions/checkout@v2

      - name: Build the Docker images
        run: |
          docker buildx build \
            --load \
            --tag ${DOCKER_REPO} \
            .

      - name: Test the Docker images
        run: docker run --rm -t ${DOCKER_REPO} yarn --version

      - name: Image history latest
        run: docker history ${DOCKER_REPO}

      - name: Images size
        run: docker image ls | grep ${DOCKER_REPO}
